steps:
# - task: DotNetCoreCLI@2
#   displayName: Restore
#   inputs:
#     command: restore
#     projects: "**/*.csproj"
#     feedsToUse: config
#     nugetConfigPath: NuGet.config

# - task: DotNetCoreCLI@2
#   displayName: Build
#   inputs:
#     projects: "**/*.csproj"
#     arguments: --configuration release

- task: DotNetCoreCLI@2
  displayName: Publish The HercPwa.Server project which will be deployed to azure
  inputs:
    command: publish
    publishWebProjects: false
    projects: 'Source/Herc.Pwa.Server/Herc.Pwa.Server.csproj'
    arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'
  enabled: true

- task: PublishBuildArtifacts@1
  displayName: Publish Artifact
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
    ArtifactName: drop
    publishLocation: Container