steps:
- script: echo Build Herc PWA Docs

- task: DeleteFiles@1
  displayName: Delete files from 
  inputs:
    Contents: ghpages
  enabled: true

- task: chrismason.vsts-docfxtasks.docfx-extension-build-task.DocFxTask@0
  displayName: Create DocFx Documentation
  inputs:
    solution: 'documentation/docfx.json'
  enabled: true

  - task: PublishBuildArtifacts@1
  displayName: Publish Artifact
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
    ArtifactName: docSite
    publishLocation: Container